import random


# with open('words.txt') as file:
#     lines = file.readlines()
#     lines = [line.rstrip() for line in lines]

#     sample_list = random.choices(lines, k=3000)
#     print(sample_list)

wholelist = [
                        'autorizar', 'embarazada', 'martir', 'imponer', 'externo', 'temperamento', 'melon', 'titular', 'clima', 'bochorno', 'mensurable', 'machista', 'imprimir', 'medicar', 'retraer',  'amplificar', 'trotar', 'hábitat', 'guante', 'eclipse', 'distraer', 'infectado', 'ubicar', 'orgulloso', 'arcilla', 'brisa', 'peluca', 'carbon', 'albañilería', 
            'descomprimir', 'excento', 'interno', 'piedra', 'troyano', 'comedia', 'drama', 'retener', 'satira', 'enceguecer', 'cavar', 'estado', 'lametear', 'gitano', 'garrafa', 'duda', 'castillo', 'abuelo', 'terremoto', 'choza', 'estrujar', 'animador', 'plastificado', 'avalancha', 
            'boton', 'enlatado', 'empanada', 'noche', 'redundante', 'trigo', 'yuyo', 'atrapar', 'psicologo', 'quebrado', 'imponer', 'acuático', 'hervir', 'maya', 'fusilero', 'atención', 'gancho', 'botella', 'repasador', 'felicitar', 'sorpresa', 'flaco', 'elegir', 'engordar', 'jadear', 'marginal', 'recreo', 'juicio', 'piedra', 'viajar', 'polemico', 
            'politico', 'escombros', 'lata', 'distorsionar', 'bizcocho', 'rematar', 'organizar', 'sofocar', 'ladron', 'desear', 'modelo', 'fanatismo', 'lujoso', 'valorar', 'monticulo', 'empeorar', 'nombramiento', 'embriagar', 'encallar', 'Dinosaurio', 'aproximación', 'perro', 'pueblo', 'poder', 'aire', 'maligno', 'contiguo', 'amasar', 'esmaltar', 
            'temblar', 'adverso', 'rivalidad', 'rabia', 'medicar', 'traumatólogo', 'infiltrado', 'prenupcial', 'cobrar', 'cortador', 'dicho', 'bicho', 'proyecto', 'desintegrarar', 'alistar', 'silvestre', 'arrestar', 'funda', 'nuclear', 'obsequiar', 'hígado', 'saciar', 'rechazar', 'tractor', 'conductor', 'chapuzon', 'asalariado', 'reemplazo', 
            'palacio', 'sol', 'luna', 'mortal', 'batería', 'riguroso', 'rio', 'rastrillo', 'aterrador', 'edificar', 'tijera', 'prestar', 'ogro', 'disciplinar', 'lobotomia', 'femenino', 'feliz', 'cardenal', 'regular', 'doliente', 'humo', 'fallecer', 'peluche', 'pala', 'rastro', 'desmarcar', 'marcar', 'endurecido', 'deprimido', 'encorvado', 'cuento', 
            'horripilante', 'balsa', 'transcendental', 'pionero', 'vecino', 'gala', 'felicitar', 'cultivo', 'pan', 'volar', 'sobresalir', 'sumergido', 'amperimetro', 'sabana', 'arremeter', 'ostentar', 'engreido', 'levitar', 'mago', 'obsesionado', 'niñera', 'catequesis', 'alimentar', 'corazonada', 'constatar', 'quemar', 'bebé', 'padre', 'madre', 'economía', 
            'divorcio', 'avalar', 'descorchar', 'incognito', 'virar', 'apocalipsis', 'zombi', 'pillar', 'decidido', 'contar', 'apestado', 'liberal', 'dormir', 'caro', 'delicioso', 'asunto', 'enrarecido', 'sotana', 'contendiente', 'insultar', 'desenterrrar', 'tabaquería', 'lamentar', 'ayuno', 'mezquino', 'considerable', 'rata', 'lengua', 'espia', 'rama', 
            'nariz', 'ballestero', 'monetarismo', 'talle', 'universidad', 'admitir', 'antología', 'junco', 'barato', 'desensillar', 'recaudo', 'confinamiento', 'asesinato', 'caballo', 'trabar', 'bárbaro', 'alegar', 'gimnasta', 'racha', 'pulmon', 'libertad', 'establezcas', 'burro', 'confidente', 'largo', 'pitufo', 'desenmascarar', 'apostar', 'amigo', 
            'proctólogo', 'triste', 'cpjín', 'conformar', 'gemelo', 'abogado', 'balbucear', 'molusco', 'desesperado', 'dignidad', 'esperanza', 'albergar', 'antiparasitario', 'parasito', 'introducir', 'afilar', 'sollozar', 'polilla', 'mosca', 'disfrutar', 'abanico', 'carpintero', 'desembolsar', 'bolsa', 'banco', 'río', 'etiqueta', 'bozal', 'hoguera', 'droga', 
            'estufa', 'amortiguador', 'desolado', 'cantaautor', 'charlar', 'zapato', 'apabullante', 'pesado', 'prender', 'asentarse', 'concurrido', 
            'volante', 'retumbar', 'ecología', 'visera', 'próximo', 'desenvolver', 'hamburguesa', 'oficial', 'revelar', 'sofocar', 'fiel', 'leal', 'criticar', 'censurar', 'optimizado', 'biografía', 'hierba', 'poner', 'mercado', 'chocolate', 'pato', 'valor', 'impartir', 'transatlantico', 'oceano', 'portero', 'contextualizar', 'canguro', 'afeitar', 'bronca',
            'dulce', 'fanatismo', 'francia', 'despegar', 'italia', 'trasluz', 'galopar', 'lejos', 'garrocha', 'primogenito', 'mutar', 'olvidar', 'equilibrista', 'callado', 'especular', 'enaltecer', 'abuelazgo', 'ensordecedor', 'traje', 'agua', 'tierra', 'ffuego', 'trágico', 'xilofón', 'fiebre', 'chancho', 'cochinada', 'lastimar', 'enlazar', 'favorecer', 'favor', 
            'encerrar', 'aceite', 'dicotómico', 'tantear', 'voltear', 'aturdido', 'archipielago', 'manguera', 'vibora', 'vaca', 'desacreditar', 'papel', 'frívolo', 'entremezclar', 'tartamudo', 'tarta', 'frio', 'calor', 'granito', 'deshidratar', 'desmerecer', 'endulzar', 'chapuzón', 'lucír', 'depender', 'bruja', 'cervecería', 'desgraciado', 'vandalizar', 'banquete', 
            'morder', 'guerra', 'albañil', 'oponer', 'crisis', 'desafinar', 'consentir', 'vigor', 'algodón', 'cortina', 'sintético', 'irreemplazable', 'pirata', 'atentado', 'pendiente', 'profanar', 'oscilar', 'quitar', 'polilla', 'farándula', 'perú', 'asesoria', 'argentina', 'uruguay', 'india', 'china', 'almendra', 'budista', 'invernar', 'subdito', 'rusia', 'velero', 
            'vela', 'familiar', 'descubrir', 'desayuno', 'sabana', 'hurto', 'entrenador', 'vago', 'cebra', 'sembrar', 'sabio', 'posición', 'purga', 'significado', 'mina', 'minero', 'traición', 'reventar', 'agarrar', 'devastado', 'desenchufar', 'trozar', 'erupción', 'volcán', 'rata', 'sapo', 'motín', 'títere', 'venezuela', 'dictador', 'afanar', 'tutela', 'bebida', 
            'substito', 'prevenir', 'enfermedad', 'padrino', 'pizza', 'bife', 'velocirraptor', 'timonel', 'pescar', 'sobrepasar', 'lector', 'isla', 'cinta', 'cintura', 'estrofa', 'deforestar', 'carnivoro', 'mapache', 'limbo', 'destapar', 'atajar', 'jugador', 'delante', 'detras', 'angustiar', 'facilitar', 'facil', 'agonizar', 'cuchara', 'disolver', 'partida', 'separador', 
            'bollo', 'caer', 'oxidado', 'conjeturar', 'axioma', 'tequila', 'matiz', 'pelo', 'baño', 'pavo', 'laguna', 'expectante', 'margen', 'cafe', 'rostizar', 'guitarra', 'jarra', 'trinchera', 'herrero', 'bebedero', 'pena', 'beso', 'pasión', 'bautizmo', 'encausar', 'bochorno', 'avergonzar', 'renovar', 'enumerar', 'matrimonio', 'escanear', 'asimilar', 'rebotar', 'consagrar', 
            'teclado', 'capitalizar', 'brasero', 'devaluado', 'grasiento', 'ecológico', 'vacunar', 'coser', 'aclarar', 'pez', 'rebaja', 'óptimo', 'tenebroso', 'programador', 'teatro', 'tetrico', 'repulsivo', 'soslayado', 'histérico', 'historia', 'curtido', 'patología', 'dicción', 'refresco', 'refrescar', 'dificultad', 'pulga', 'intento', 
            'metamorfosis', 'desencajar', 'abuela', 'alambrado', 'congestión', 'almacén', 'almacenar', 'burbuja', 'burbujeante', 'feriado', 'apaciguar', 'reinsertar', 'picar', 'garganta', 'insensibilidad', 'arrear', 'garrote', 'abrochar', 'reventar', 'cinematografía', 'correr', 'manotazo', 'subordinado', 'película', 'fotografía', 'feto', 'extraterrestre', 'alienigena', 'índice', 
            'espantar', 'cola', 'mentir', 'mentiroso', 'partir', 'lenteja', 'despertar', 'preparar', 'neutralizar', 'neutral', 'picotear', 'digital', 'analógico', 'telegrafo', 'parto', 'acribillar', 'fertil', 'sistema', 'sanción', 'raro', 'estratificado', 'lamer', 'asumir', 'relatar', 'saldo', 'panqueque', 'vino', 'helada', 'helado', 'contrario', 'complejo', 'marmota', 'lobo', 'marino', 
            'serpentina', 'conciencia', 'conocimiento', 'frasco', 'redondo', 'avasallar', 'tacón', 'maiz', 'conglomerado', 'urbano', 'puerto', 'buque', 'lácteo', 'mercurio', 'saturno', 'exprimir', 'kazajastan', 'pico', 'australia', 'belleza', 'jabon', 'carcel', 'jaula', 'guardia', 'extrovertido', 'introveritdo', 'sociable', 'melancolía', 'psicopata', 'amable', 'amado', 'presagio', 'reventar', 
            'recolectar', 'poste', 'correo', 'intubar', 'manteca', 'muelle', 'arremeter', 'aplastar', 'construir', 'jugar', 'percibir', 'dictador', 
            'democracia', 'reinado', 'rey', 'pincel', 'senado', 'doctor', 'administrador', 'trozo', 'daño', 'remate', 'ficción', 'compartir', 'desterrado', 'tono', 'musica', 'banda', 
            'aderezo', 'punzante', 'fanatismo', 'seguidor', 'gaucho', 'gas', 'reinicio', 'brujería', 'pocion', 'noticiero', 'prevención', 'epidemia', 'exaltar', 'congregación', 'entretenido', 'caña', 'acondicionado', 'condición', 'prehistoria', 'adormecido', 'temporal', 'jugado', 'nuera', 'suegro', 'caldo', 'farsa', 'estafa', 'faltante', 'error', 'corregir', 'estropear', 'tuerto', 'degollado']
print(len(wholelist))